version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3

    steps:
      - checkout

      - restore_cache:
          keys:
            - node_modules-checksum-{{ checksum "yarn.lock" }}
            - node_modules-

      - run: yarn install --frozen-lockfile

      - save_cache:
          key: node_modules-checksum-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run: yarn lint

      - run: yarn test

      - run: yarn build
